/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules;

import javax.xml.datatype.XMLGregorianCalendar;

import org.apache.commons.lang.NotImplementedException;
import org.datacontract.schemas._2004._07.eztaxwebservice.ArrayOfAddressData;
import org.datacontract.schemas._2004._07.eztaxwebservice.ArrayOfTaxData;
import org.mule.api.ConnectionException;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Connect;
import org.mule.api.annotations.ConnectionIdentifier;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Disconnect;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.ValidateConnection;
import org.mule.api.annotations.param.ConnectionKey;

/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */
@Connector(name="eztax", schemaVersion="1.0-SNAPSHOT")
public class EZTaxConnector
{
    /**
     * Configurable
     */
    @Configurable
    private String username;
    
    @Configurable
    private String password;
    
    

    /**
     * Connect
     *
     * @param username A username
     * @param password A password
     * @throws ConnectionException
     */
    @Connect
    public void connect(@ConnectionKey String username, String password)
        throws ConnectionException {
        /*
         * CODE FOR ESTABLISHING A CONNECTION GOES IN HERE
         */
    }

    /**
     * Disconnect
     */
    @Disconnect
    public void disconnect() {
        /*
         * CODE FOR CLOSING A CONNECTION GOES IN HERE
         */
    }

    /**
     * Are we connected
     */
    @ValidateConnection
    public boolean isConnected() {
        return true;
    }

    /**
     * Are we connected
     */
    @ConnectionIdentifier
    public String connectionId() {
        return "001";
    }

    /**
     * Custom processor
     *
     * {@sample.xml ../../../doc/EZTax-connector.xml.sample eztax:my-processor}
     *
     * @param content Content to be processed
     * @return Some string
     * 
     * <calculate-taxes strategy="FIPS"
customer-type="RESIDENTIAL" sale="true" service-class="PRIMARY_LOCAL" .../>
     */
    @Processor
    public ArrayOfTaxData calculateTaxes(String strategy,
                                         String customerType,
                                         Boolean sale,
                                         String serviceClass)
    {
        throw new NotImplementedException();
    }
    
    //<calculate-adjustment strategy="FIPS" customer-type="RESIDENTIAL" sale="true" service-class="PRIMARY_LOCAL" .../>
    @Processor
    public ArrayOfTaxData calculateAdjustment(String strategy,
                                      String customerType,
                                      Boolean sale,
                                      String serviceClass)
    {
        throw new NotImplementedException();
    }
    
    //<get-address pcode="#[map-payload:anIntegerCode]"/>
    @Processor
    public ArrayOfAddressData getAddress(Long pCode)
    {
        throw new NotImplementedException();
    }
    //<get-tax-category taxCode="#[map-payload:anIntegerTaxCode]"/>
    @Processor
    public String getTaxCategory(Integer taxCode)
    {
        throw new NotImplementedException();
    }
    
    //<get-tax-description pcode="#[map-payload:anIntegerCode]"/>
    @Processor
    public String getTaxDescription(Integer taxCode)
    {
        throw new NotImplementedException();
    }
    
    //<convert-fips-to-pcode fips="#[map-payload:fipsCode]"/>
    @Processor
    public Long convertFipsToPcode(String fips)
    {
        throw new NotImplementedException();
    }
    
    //<convert-npanxx-to-pcode npanxxCode="#[map-payload:npanxxCode]"/>
    @Processor
    public Long convertNpanxxToPcode(String npanxxCode)
    {
        throw new NotImplementedException();
    }
    
    //<convert-zip-to-pcode zipCode="#[map-payload:aZipCode]"/>
    @Processor
    public Long convertZipToPcode(String zipCode)
    {
        throw new NotImplementedException();
    }
    
    //<get-server-time/>
    @Processor
    public XMLGregorianCalendar getServerTime()
    {
        throw new NotImplementedException();
    }
    

    /**
     * Returns the username.
     * 
     * @return  with the username.
     */
    
    public String getUsername()
    {
        return username;
    }

    /**
     * Sets the username. 
     *
     * @param username  with the username.
     */
    
    public void setUsername(String username)
    {
        this.username = username;
    }

    /**
     * Returns the password.
     * 
     * @return  with the password.
     */
    
    public String getPassword()
    {
        return password;
    }

    /**
     * Sets the password. 
     *
     * @param password  with the password.
     */
    
    public void setPassword(String password)
    {
        this.password = password;
    }
}
